# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)
print(np.show_config())

1.16.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/VINAYA/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/VINAYA/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/VINAYA/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\l

#### 3. Create a null vector of size 10

In [4]:
arr = np.zeros(10,dtype=int)
print(arr)

[0 0 0 0 0 0 0 0 0 0]


#### 4.  How to find the memory size of any array

In [5]:
print("%d bytes" % (arr.size * arr.itemsize))
  

40 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [18]:
help([np])
np?


#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [19]:
arr = np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [10]:
a=np.random.randint(10,50,41)
print(a)

[28 11 11 29 37 15 37 12 38 36 13 43 22 39 37 41 36 10 48 37 32 30 35 48
 33 31 38 21 19 48 11 39 23 26 39 13 20 36 46 22 29]


#### 8.  Reverse a vector (first element becomes last)

In [11]:
b=a[::-1]
print(b)

[29 22 46 36 20 13 39 26 23 39 11 48 19 21 38 31 33 48 35 30 32 37 48 10
 36 41 37 39 22 43 13 36 38 12 37 15 37 29 11 11 28]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
a=np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [15]:
a=[1,2,0,0,4,0]
c=np.array(a)
b =np.nonzero(c)
print(b)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [22]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [23]:
print(np.random.rand(3,3,3))

[[[0.66152013 0.93583632 0.93667582]
  [0.56415072 0.76545566 0.59577937]
  [0.94291399 0.91176319 0.09502673]]

 [[0.22036623 0.93548097 0.59310911]
  [0.93462403 0.53541271 0.97622813]
  [0.92116534 0.39534408 0.24256791]]

 [[0.90613721 0.3351243  0.45160753]
  [0.6607431  0.47171903 0.6436758 ]
  [0.93314778 0.54693456 0.07477048]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [28]:
a=np.random.rand(10,10)
print(a)
print("min",np.min(a))
print("max",np.max(a))

[[0.37421915 0.05525578 0.94528437 0.60854047 0.03588984 0.76957026
  0.87963759 0.38852842 0.42483322 0.8915905 ]
 [0.04739958 0.54626948 0.20305792 0.31093603 0.9466952  0.13076009
  0.21943189 0.43745737 0.62498085 0.28836138]
 [0.5252648  0.7489782  0.61556154 0.51385107 0.9019601  0.15583932
  0.27113326 0.9156816  0.54303141 0.64539672]
 [0.03778448 0.63612305 0.3265144  0.56670386 0.79603651 0.88041926
  0.80964493 0.4836005  0.22625948 0.92736851]
 [0.82260632 0.64580297 0.15515805 0.83839741 0.00293261 0.46859293
  0.81665173 0.50731459 0.00924851 0.14522561]
 [0.73321061 0.81221989 0.33914068 0.52227473 0.99236551 0.56663853
  0.7920747  0.4904824  0.17018536 0.77812552]
 [0.82281117 0.13074909 0.16350734 0.33405828 0.02799128 0.95682367
  0.18812632 0.7517589  0.34565307 0.37925026]
 [0.46350804 0.30317655 0.35511677 0.97405993 0.88549646 0.39141589
  0.94560303 0.06921338 0.82210929 0.15316707]
 [0.47135975 0.60406601 0.17814105 0.15997552 0.80766149 0.43472182
  0.11239312

#### 14. Create a random vector of size 30 and find the mean value

In [38]:
a=np.random.rand(10,3)

print(a.size)
print(np.mean(a))

30
0.5940829254359714


#### 15. Create a 2d array with 1 on the border and 0 inside

In [47]:
n=int(input())
a=np.ones((n,n))
a[1:-1,1:-1] = 0
print(a)

5
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [4]:
m,n=map(int,input().split())
a=np.ones((m,n))
a=np.pad(a,1,'constant',constant_values=0)

print(a)

3 3
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [5]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [6]:
x = np.ones((3,3))

x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [14]:
a=np.random.rand(336)
c=a[99]
print(c)
b=a.reshape(6,7,8)
np.where(b==c)

0.6568655847829501


(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))